### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-supermarket#11]
We need to be able to load statically a Configuration file in the binary.

I think there was a nice crate to do the whole deserialiazation into a stuct,

- [x] Loading a configuration from file (dev & prod) in the binary #13 
  https://github.com/AdExNetwork/adex-validator-stack-rust/blob/master/primitives/src/config.rs#L9
  - [x] We can later add the option to the binary (`clap`) #13 
  - [x] Log the environment (dev/prod) and configuration #13 
- Timeouts:
  - [x] fetching new campaigns from the Market #13 
  - [x] updating the cache Campaigns statuses (the batch action) #13 
  - [x] Validator Request timeout #13 
  If validator is offline or there is connection issue it shouldn't fail the whole Update action of Campaigns statuses

- [x] recency (4 minutes default from https://github.com/AdExNetwork/adex-market/blob/eed1f7f0bfa89fb5e0cf7061f10b8a6492299c5c/cfg.js#L9) #13 
- [x] `limitedIdentityEarningsLimit` from https://github.com/AdExNetwork/adex-market/blob/eed1f7f0bfa89fb5e0cf7061f10b8a6492299c5c/cfg.js#L13 #13 
- [x] Fetch campaigns from Market every X secs/mins #13 
- [x] Update campaigns statuses (from validators) every X secs/mins #13
