### ISSUE TITLE
Decoupling the Supermarket from the Market

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-supermarket#23]
Since the Supermarket is very dependant on the Market to retrieve the campaigns, it makes the Supermarket work quite obsolete (apart from safety & performance).
This is why we want to make the changes to decouple it from the Market and instead fetch the campaigns from the validators in a configured list . 

### Changes:

1. [x] PR #24 Configuration list of validators to fetch the campaigns from (instead of the market)
2. [x] PR #24 Fetch the active (channel.valid_until > Now) campaigns (and compute their status)

### TODOs:
- [x] ~Check ChannelId when Channel is fetched from Validator:~ This is not really required since the `get_status` will check both validators and if they don't agree a bad status will be returned 
https://github.com/AdExNetwork/adex-validator-stack-rust/blob/dev/adapter/src/ethereum.rs#L162-L173
- [x] Test `Cache::update` & `Cache::fetch_new_campaigns` (after initialization)

The flow stays the same:
- :heavy_check_mark:  On start-up initialize the Cache by querying each validator for Channels and compute the Status - repeat every couple of minutes
- :heavy_check_mark: Compute the latest status by querying the Leader/Follower for latest messages - repeat every couple of seconds

**Comment by elpiel** [comment]
Closing issue as all tasks are solved.

This is not really required since the `get_status` will check all validators and if they don't agree a bad status will be returned:

> Check ChannelId when Channel is fetched from Validator:
> https://github.com/AdExNetwork/adex-validator-stack-rust/blob/dev/adapter/src/ethereum.rs#L162-L173~
