### ISSUE TITLE
Impl get_status

### ISSUE THREAD

**Issue by elpiel** [AdExNetwork/adex-supermarket#5]
Resolves https://github.com/AdExNetwork/adex-market/issues/5

- [x] #6 enum Status
- [x] #6 fn get_status
  - [ ] test
- [x] #6 fn is_finalized
  - [x] #10 test
- [x] #7 fn is_date_recent + testing @simzzz  
- [x] #7 fn is_initializing + testing @simzzz 
- [x] #6 fn is_offline
  - [x] #10 test
- [x] #7 fn is_disconnected + testing @simzzz 
- [x] #17 fn is_rejected_state + testing @simzzz 
- [x] #17 fn is_unhealthy + testing @simzzz 
- [x] #20 fn is_active + testing @simzzz 
- [x] #20 fn is_ready + testing @simzzz

**Comment by elpiel** [comment]
Additional check was added (that exists in JS) in PR https://github.com/AdExNetwork/adex-supermarket/pull/37 for `channel_active_from` when evaluating the Active & Waiting statuses

This still needs tests for the `get_status` function itself
